export const browserCoreExamples = [
  "gensparx browser status",
  "gensparx browser start",
  "gensparx browser stop",
  "gensparx browser tabs",
  "gensparx browser open https://example.com",
  "gensparx browser focus abcd1234",
  "gensparx browser close abcd1234",
  "gensparx browser screenshot",
  "gensparx browser screenshot --full-page",
  "gensparx browser screenshot --ref 12",
  "gensparx browser snapshot",
  "gensparx browser snapshot --format aria --limit 200",
  "gensparx browser snapshot --efficient",
  "gensparx browser snapshot --labels",
];

export const browserActionExamples = [
  "gensparx browser navigate https://example.com",
  "gensparx browser resize 1280 720",
  "gensparx browser click 12 --double",
  'gensparx browser type 23 "hello" --submit',
  "gensparx browser press Enter",
  "gensparx browser hover 44",
  "gensparx browser drag 10 11",
  "gensparx browser select 9 OptionA OptionB",
  "gensparx browser upload /tmp/file.pdf",
  'gensparx browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "gensparx browser dialog --accept",
  'gensparx browser wait --text "Done"',
  "gensparx browser evaluate --fn '(el) => el.textContent' --ref 7",
  "gensparx browser console --level error",
  "gensparx browser pdf",
];
